# Generated by Django 5.1.2 on 2024-10-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.CharField(max_length=2),
        ),
    ]
